### ISSUE TITLE
There is no RTSP_URL variable in docker-compose.yml, so how do i properly connect my camera?

### ISSUE THREAD

**Issue by iaroshvictor** [Ullaakut/WebRTCCTV#9]

**Comment by Ullaakut** [comment]
Hi!

You can easily do that by changing the URI that is specified here: https://github.com/Ullaakut/WebRTCCTV/blob/b2005a1ed4bfe85639259f068ab84847229f4456/webapp/static/src/index_tmpl.js#L116

and then rebuilding the docker images. If you need more info on how to do that, I'll gladly help.

If you feel like contributing, don't hesitate to make a few changes to the docker image to use an environment variable for the RTSP_URI, that would be a useful change :)

May I ask why you are using WebRTCCTV?

**Comment by iaroshvictor** [comment]
Thank you for your answer. I'll do my best to check the web-interface so we could make it dynamically.

**Comment by iaroshvictor** [comment]
I need to stream to a webpage rtsp stream from a couple of ip cameras. By so far using webrtc is a good solution.

**Comment by Ullaakut** [comment]
Alright, seems like a good solution yes. I had a version of the WebRTCCTV that handled multiple cameras at the same time somewhere, if you're interested I can look for it or recode it quickly this weekend :)

Also if WebRTC ends up not working for you, I have other solutions. Especially if infrastructure is a problem (since WebRTC forces you to open a bunch of ports in your firewalls).

**Comment by iaroshvictor** [comment]
Thanks, 
I'll do my best to get deeper into your code in order to understand how the things goes. If you have any other solutions for streaming rtsp, i'd be glad to read about them.

**Comment by Ullaakut** [comment]
Not sure if you'll find a lot to read about it but at my previous job we ended up choosing to use https://jsmpeg.com 

Basically we transformed the H264 stream into MPEG and used this library to decode it in the frontend. It's surprisingly fast, low latency etc. The only downside is that since the decoding is done in the browser, it uses some of the client's CPU.

**Comment by Ullaakut** [comment]
(But compared to WebRTC, it was really easy and quick to implement, so unless you have another reason to sue WebRTC I suggest you take a look into it :))

**Comment by iaroshvictor** [comment]
Transforming the stream from H264 to MPEG is a very heavy for CPU (usually, tried to use motion and ffmpeg). That's why i'm trying to find a solution to stream the raw format.

**Comment by Ullaakut** [comment]
Then yep feel free to look into WebRTC, and let me know if I can help! :)

**Comment by iaroshvictor** [comment]
Seems like Webrtc has some issues about windows clients. Have you tested this before? I am able to view the video from a Linux device , but not on a Windows one. The same issue happened with https://github.com/mpromonet/webrtc-streamer this one.

**Comment by Ullaakut** [comment]
Mh no never had this issue, what’s the browser you used on the Windows machine?

WebRTCCTV was tested on all devices even mobiles and TVs and was working fine with Firefox, Chrome, Opera and Safari IIRC

On 18 Oct 2018, at 10:41, iaroshvictor <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems like Webrtc has some issues about windows clients. Have you tested this before? I am able to view the video from a Linux device , but not on a Windows one. The same issue happened with https://github.com/mpromonet/webrtc-streamer this one.

**Comment by iaroshvictor** [comment]
Looks like the problem is not in WEBRTC but in h264 poor support on Windows browsers

**Comment by Ullaakut** [comment]
Try using an up to date version of Google Chrome or Firefox, and make sure you have the media feature pack installed in Windows
